[package]
name = "gazou"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deadpool-postgres = "0.14.0"
env_logger = "0.11.5"
log = "0.4.22"
ntex = { version = "2.6.0", features = ["tokio"] }
