[package]
name = "gazou"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deadpool-postgres = "0.12.1"
env_logger = "0.11.3"
log = "0.4.21"
ntex = { version = "1.2.1", features = ["tokio"] }
